name: kite_bird
description: An E-Wallet and a payment gateway.
version: 0.0.1
author: Eddie|Genius <elyudde@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  # pedantic: ^1.8.0+1
  aqueduct: ^3.0.0
  mongo_dart: ^0.3.6
  password: ^1.0.0
  random_string: ^1.1.0
  http: ^0.12.0+2
  # xml: ^3.5.0
  crypto: ^2.1.3
  tripledes: ^2.1.0
  # mailer: ^3.0.4

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
